<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
    <div class="container">

        <div class="section-title" data-aos="fade-up">
            <h3>Contact Us</h3>
        </div>

        <div class="row">

            <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div class="contact-about">
                    <h3>Credit Collection Partners</h3>
                    <p>CCP was built on the foundation of Service, Compliance, and Results. These are the principles
                        that have made CCP a thriving Illinois based company since our inception in 1938.</p>
                    <div class="social-links text-center text-lg-left pt-3 pt-lg-0">
                        <a href="#" class="twitter"><i class="bx bxl-twitter bx-lg"></i></a>
                        <a href="#" class="facebook"><i class="bx bxl-facebook bx-lg"></i></a>
                        <a href="#" class="linkedin"><i class="bx bxl-linkedin bx-lg"></i></a>
                    </div>
                </div>
                <div class="contact-log">
                    <img src="assets/img/logo/logo.png" style="max-width:300px;margin-top:25px;" />
                </div>
                <div class="copyright-section">
                    <div class="mr-lg-auto text-center text-lg-left">
                        <div class="copyright">
                            &copy; Copyright <strong><span>Company</span></strong>. All Rights Reserved
                        </div>
                        <div class="credits">
                            <!-- All the links in the footer should remain intact. -->
                            <!-- You can delete the links only if you purchased the pro version. -->
                            <!-- Licensing information: https://bootstrapmade.com/license/ -->
                            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexor-free-multipurpose-bootstrap-template/ -->
                            Designed by Chrisman Creative
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mt-4 mt-md-0" data-aos="fade-up" data-aos-delay="200">
                <div class="info">
                    <div>
                        <i class="ri-mail-send-line"></i>
                        <p><a href="mailto:contact@example.com">contact@example.com</a></p>
                    </div>

                    <div>
                        <i class="ri-phone-line"></i>
                        <p><a href="tel:123-456-7890">Phone: (217) 284-4400 </a></p>
                    </div>


                    <div>
                        <i class="ri-phone-line"></i>
                        <p><a href="sms:123-456-7890">Text: CCP to 43783</a></p>
                    </div>
                    <div>
                        <i class="ri-phone-line"></i>
                        <p>Mon-Fri 9am - 5pm </p>
                    </div>
                    <div>
                        <i class="ri-map-pin-line"></i>
                        <p><a href="https://www.google.com/maps/place/vcaqua/@40.698303,-73.9910377,17z/data=!4m8!1m2!2m1!1sA108+Adam+Street+New+York,+NY+535022!3m4!1s0x89c25a35d886ece5:0x62e24eacc2d0fc67!8m2!3d40.698303!4d-73.988849" target="_blank">905 West Spresser Street <br/>Taylorville, IL 62568</a></p>
                    </div>
                    <div>
                        <iframe border="0" frameborder="0" style="border: 0; height:90px; width:200px;" src="https://seal-stlouis.bbb.org/frame/ruhzbul/bbb-310569227.png?chk=306DB23B51"></iframe>
                        <div style="text-align: center;width: 200px;font-weight: 600;font-size: .9em;">Business Details<br/>& Customer Reviews</div>
                    </div>

                </div>
            </div>

            <div class="col-lg-5 col-md-12" data-aos="fade-up" data-aos-delay="300">
                <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                        <div class="validate"></div>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                        <div class="validate"></div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                        <div class="validate"></div>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message/Customer Review"></textarea>
                        <div class="validate"></div>
                    </div>
                    <div class="mb-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center"><button type="submit">Send</button></div>
                </form>
            </div>

        </div>

    </div>
</section><!-- End Contact Section -->

</main><!-- End #main -->

<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>