<!-- Vendor JS Files -->
<script src="assets/vendor/jquery/jquery.min.js"></script>
<script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="assets/vendor/php-email-form/validate.js"></script>
<script src="assets/vendor/jquery-sticky/jquery.sticky.js"></script>
<script src="assets/vendor/venobox/venobox.min.js"></script>
<script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="assets/vendor/aos/aos.js"></script>
<script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
<script src="assets/vendor/counterup/counterup.min.js"></script>

<!-- Template Main JS File -->
<script src="assets/js/main.js"></script>
<script src="assets/js/about/main.js"></script>
<script src="assets/js/readmore.min.js"></script>

<script type="text/javascript">
    $('#team .member p.first-team-member').readmore({
        speed: 75,
        lessLink: '<a href="#">Read less</a>',
        collapsedHeight: 100
    });
    $('#team .member p.second-team-member').readmore({
        speed: 75,
        lessLink: '<a href="#">Read less</a>',
        collapsedHeight: 100
    });
    $('#team .member p.third-team-member').readmore({
        speed: 75,
        lessLink: '<a href="#">Read less</a>',
        collapsedHeight: 100
    });
    $('#team .member p.fourth-team-member').readmore({
        speed: 75,
        lessLink: '<a href="#">Read less</a>',
        collapsedHeight: 100
    });

    $('#data-security .card .card-text').readmore({
        speed: 75,
        lessLink: '<a href="#">Read less</a>',
        collapsedHeight: 250
    });
    $('#fair-collection-practices .card .card-text').readmore({
        speed: 75,
        lessLink: '<a href="#">Read less</a>',
        collapsedHeight: 250
    });

    <?php
    if(isset($_GET['active']) && $_GET['active'] == 'circuit-clerks') { ?>
    $('#myTab a[href="#home"]').tab('show');
    <?php } else if (isset($_GET['active']) && $_GET['active'] == 'states-attorneys') { ?>
    $('#myTab a[href="#profile"]').tab('show');
    <?php } ?>
</script>

<!-- widget container, must have this exactly "id" property -->
<div id="lv_chatwidget"></div>
<!-- embed script from Livevox CDN for chat -->
<script src="https://chat-cdn.livevox.com/chat/chat-widget-1.0.min.js"></script>
<script>
    LVChatWidget.connect({
        url: 'https://chat.na4.livevox.com/chat/connect', //required, url of chat gateway. Client should know which environment they are in
        uuid: '81487df008f9f31fe053ae20650ad0b9', //required, client uuid
        departments: ['Example'], //required, list of available departments to Chat with. Values must match with Chat Routing Token
        title: 'Chat With Us', //optional, initial chat title
        avatarUrl: 'https://client.website.com/assets/agentAvatar.svg', //optional, agent default avatar
        autoCloseTimeout: 300, //optional, timeout used to disconnect the customer after inactivity; default = 300 seconds
    });
</script>

</body>

</html>