<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>CCP</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <?php if(isset($assetDir)){ ?>
    <link href="assets/css/<?= $assetDir ?>/style.css" rel="stylesheet">
    <?php } ?>

    <!-- Custom CSS File -->
    <link href="assets/css/custom_style.css" rel="stylesheet">
    <link href="assets/css/custom_style_alt1.css" rel="stylesheet">
    <?php if(isset($assetDir)){ ?>
    <link href="assets/css/<?= $assetDir ?>/custom_style.css" rel="stylesheet">
    <?php } ?>

    <?php
    $backgroundImage = null;
    if($assetDir == 'markets'){
        $backgroundImage = 'assets/img/bg/markets.jpg';
    }
    elseif ($assetDir == 'technology'){
        $backgroundImage = 'assets/img/bg/technology.jpg';
    }
    elseif ($assetDir == 'consumer-reviews' || $assetDir == 'client-testimonials'){
        $backgroundImage = 'assets/img/bg/reviews.jpg';
    }
    elseif ($assetDir == 'about' || $assetDir == 'philanthropy' || $assetDir == 'policies'){
        $backgroundImage = 'assets/img/bg/about.jpg';
    }

    if(isset($backgroundImage)){
        ?>
    <style type="text/css">
        #hero{
            background-image: url('<?= $backgroundImage ?>');
        }
    </style>
    <?php
    }
    ?>
</head>