<!-- ======= Header ======= -->
<header id="header">
    <div class="container d-flex">

        <div class="logo mr-auto">
            <h1 class="text-light"><a href="index.php"><span><img src="https://res.cloudinary.com/df5atw3fa/image/upload/v1625084026/CCP/logo/CCP_WordMark_V2_lx1ylh.svg"></span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="active"><a href="index.php">Home</a></li>
                <li class="drop-down"><a href="about.php">About</a>
                    <ul>
                        <li class="show-mobile"><a href="about.php">About Us</a></li>
                        <li><a href="about.php#team">Leadership Team</a></li>
                        <li><a href="about.php#about-boxes">Values</a></li>
                        <li><a href="about.php#awards">Awards & Memberships</a></li>
                        <li><a href="technology.php">Technology</a></li>
                        <li><a href="philanthropy.php">Philanthropy</a></li>
                        <li><a href="policies.php">Policies</a></li>
                    </ul>
                </li>
                <li><a href="markets.php">Markets</a></li>
                <li><a href="consumer-reviews.php">Consumer Reviews</a></li>
                <li><a href="client-testimonials.php">Client Testimonials</a></li>
                <!--<li class="drop-down"><a href="">Drop Down</a>
                  <ul>
                    <li><a href="#">Drop Down 1</a></li>
                    <li class="drop-down"><a href="#">Drop Down 2</a>
                      <ul>
                        <li><a href="#">Deep Drop Down 1</a></li>
                        <li><a href="#">Deep Drop Down 2</a></li>
                        <li><a href="#">Deep Drop Down 3</a></li>
                        <li><a href="#">Deep Drop Down 4</a></li>
                        <li><a href="#">Deep Drop Down 5</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Drop Down 3</a></li>
                    <li><a href="#">Drop Down 4</a></li>
                    <li><a href="#">Drop Down 5</a></li>
                  </ul>
                </li>-->
            </ul>
        </nav><!-- .nav-menu -->

    </div>
</header><!-- End Header -->