<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
    <div class="container aos-init aos-animate" data-aos="fade-in">
        <h1 style="text-align:center;"><?= $heroTitle ?></h1>
        <!--<h2 style="text-align:center;">We are team of talanted designers making websites with Bootstrap</h2>-->
        <!-- <a href="#about" class="btn-get-started scrollto">Get Started</a> -->
    </div>
</section><!-- End Hero -->

<main id="main">