<!-- ======= Top Bar ======= -->
<section id="topbar" class="d-none d-lg-block">
    <div class="container d-flex">
        <div class="contact-info mr-auto">
            <ul>
                <!--<li><i class="icofont-envelope"></i><a href="mailto:contact@example.com">contact@example.com</a></li>-->
                <li><i class="icofont-phone"></i><a href="tel:800-331-9772">Phone: (800) 331-9772</a></li>
                <li><i class="icofont-phone"></i><a href="tel:123-456-7890">Phone: (217) 284-4400</a></li>
                <li><i class="icofont-hand-up"></i><a href="sms:123-456-7890">Text: CCP to 43783</a></li>
                <li><i class="icofont-clock-time icofont-flip-horizontal"></i> Mon-Fri 8am - 5pm</li>
                <li><i class="icofont-pin icofont-flip-horizontal"></i><a href="https://www.google.com/maps/place/vcaqua/@40.698303,-73.9910377,17z/data=!4m8!1m2!2m1!1sA108+Adam+Street+New+York,+NY+535022!3m4!1s0x89c25a35d886ece5:0x62e24eacc2d0fc67!8m2!3d40.698303!4d-73.988849" target="_blank">905 West Spresser Street, Taylorville, IL 62568</a></li>
            </ul>

        </div>
        <!--<div class="cta">
          <a href="#" class="scrollto">Pay Online</a>
          <a href="#" class="scrollto">Client Login</a>
        </div>-->
    </div>
</section>